- hosts: master
  become: yes
  tasks:
    - name: Remove Kubeconfig
      file:
        path: ./kubeconfig
        state: absent

    - name: Copy Kubeconfig to local
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig
        flat: yes