- hosts: all
  tasks:
    - name: Module Probe
      shell: sudo modprobe br_netfilter

    - name: Be sure the module is loaded
      shell: |
        lsmod | grep br_netfilter

    - name: Enable required Sysctl Parameter
      shell: |
        sudo tee /etc/sysctl.d/k8s.conf <<EOF
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF
        
    - name: Apply the changes
      shell: sudo sysctl --system

    - name: Load BR on boot
      shell: |
        echo "br_netfilter" | sudo tee /etc/modules-load.d/br_netfilter.conf

    - name: Restart kubelet
      shell: |
        sudo systemctl restart kubelet