- hosts: all
  become: yes
  tasks:
    - name: Create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: allow ubuntu to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: setup authorized key
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Disable Swap
      shell: |
        sed -i '/swap/d' /etc/fstab
        swapoff -a