- hosts: master
  become: yes
  tasks:
    - name: Install Kubectl on master
      apt:
        name: kubectl=1.30.*
        state: present
        force: yes
    - name: Initialize cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: vagrant
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Install Pod Network
      become: yes
      become_user: vagrant
      shell: "kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml >> pod_network_setup.txt"
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
