apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notes
  namespace: notes
spec:
  template:
    spec:
      containers:
        - image: docker.io/lordrahl/notes:v3
          env:
            - name: TARGET
              value: "Go Sample v1"