loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    size: 10Gi


promtail:
  enabled: true

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
  image:
    tag: latest

prometheus:
  enabled: false

