- name: Installing Apache
  hosts: all
  become: true
  tasks:
    - name: Update repository index
      apt:
        update_cache: yes

    - name: Install apache2 package
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        